  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/pt-br/"

  [[main]]
  name = "Filmes"
  weight = 230
  identifier = "filmes"
  url = "/pt-br/film/"
  #parent = "portfolio"

    [[main]]
  name = "Reels"
  weight = 200
  identifier = "reels"
  url = "/pt-br/reels/"
  #parent = "portfolio"

      [[main]]
  name = "Projetos"
  weight = 210
  identifier = "projetos"
  url = "/pt-br/"
  #parent = "portfolio"

  [[main]]
  name = "Sobre"
  weight = 400
  identifier = "sobre"
  url = "/pt-br/about/"

    [[main]]
  name = "CV"
  weight = 500
  identifier = "cv"
  url = "/pt-br/cv/"

  [[main]]
  name = "Contato"
  weight = 600
  identifier = "contato"
  url = "/pt-br/contato/"


  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/pt-br/imprint/"
