  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Films"
  weight = 230
  identifier = "films"
  url = "/film/"
  #parent = "portfolio"

    [[main]]
  name = "Reels"
  weight = 200
  identifier = "reels"
  url = "/reels/"
  #parent = "portfolio"

      [[main]]
  name = "Projects"
  weight = 210
  identifier = "projects"
  url = "/"
  #parent = "portfolio"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

    [[main]]
  name = "Resume"
  weight = 500
  identifier = "resume"
  url = "/resume/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"


  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
