  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/pt-br/"

  [[main]]
  name = "Portfólio"
  weight = 200
  identifier = "portfolio"
  #url = "/pt-br/portfolio/"

  [[main]]
  name = "Filmes"
  weight = 210
  identifier = "filmes"
  url = "/pt-br/film/"
  parent = "portfolio"

    [[main]]
  name = "Reels"
  weight = 220
  identifier = "reels"
  url = "/pt-br/reels/"
  parent = "portfolio"

      [[main]]
  name = "Projetos"
  weight = 230
  identifier = "projetos"
  url = "/pt-br/post/"
  parent = "portfolio"

    #[[main]]
  #name = "3D"
  #weight = 230
  #identifier = "3D"
  #url = "/pt-br/3d/"
  #parent = "portfolio"

  [[main]]
  name = "Sobre"
  weight = 400
  identifier = "sobre"
  url = "/pt-br/about/"


  #[[main]]
  #name = "Accomplishments"
  #weight = 500
  #identifier = "accomplishments"

  #[[main]]
  #name = "Awards"
  #weight = 510
  #identifier = "awards"
  #url = "/pt-br/awards/"
  #parent = "accomplishments"

  #[[main]]
  #name = "Certifications"
  #weight = 520
  #identifier = "certifications"
  #url = "/pt-br/certifications/"
  #parent = "accomplishments"

  [[main]]
  name = "Contato"
  weight = 600
  identifier = "contato"
  url = "/pt-br/contato/"


  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/pt-br/imprint/"
